INSERT INTO users (id, username, password, email, role, blocked) VALUES ((SELECT nextval('user_id_sequence')), 'User', '$2a$08$V9fGuOE9X11UmaVr0FR3Qu.T54EbaMnDxlsQAbnwaawJi0nFHXalO', 'andrew_gosenz@gmail.com', 'USER', false);
-- password: User2002
INSERT INTO users (id, username, password, email, role, blocked) VALUES ((SELECT nextval('user_id_sequence')), 'Karlo', '$2a$12$PZARDqfqZGsnoylgkh7/IeIQfNFgDB7om6Fka/RHMs2z9MwnqHxFW', 'karlo.velinni@gmail.com', 'USER', false);
-- password: Karlo2002
INSERT INTO users (id, username, password, email, role, blocked) VALUES ((SELECT nextval('user_id_sequence')), 'Marko', '$2a$12$Nd9p3NuN8M71QlpWtb.djOkMfAQ2ZqHnIcFVqh2I4j8EBSJ3yxDSu', 'marko.kavelo@gmail.com', 'USER', true);
-- password: Marko2002
INSERT INTO users (id, username, password, email, role, blocked) VALUES ((SELECT nextval('user_id_sequence')), 'Admin', '$2a$08$8IlYUUkkbhYdiNrZuiNVbuLmIq0eDmRnFXpUHFjtPSCqdWeGOCp86', 'joe.pistone@gmail.com', 'ADMIN', false);
-- password: Admin2002

INSERT INTO topics (id, title, category, creation_date, actual, creator_id) VALUES ((SELECT nextval('topic_id_sequence')), 'Spring Framework', 'TECHNOLOGIES', '2022-04-15', true, (SELECT id FROM users WHERE username LIKE 'Admin'));
INSERT INTO topics (id, title, category, creation_date, actual, creator_id) VALUES ((SELECT nextval('topic_id_sequence')), 'Spring Boot Framework', 'TECHNOLOGIES', '2022-05-02', true, (SELECT id FROM users WHERE username LIKE 'Admin'));
INSERT INTO topics (id, title, category, creation_date, actual, creator_id) VALUES ((SELECT nextval('topic_id_sequence')), 'Tesla - accumulators', 'CARS', '2022-03-02', false, (SELECT id FROM users WHERE username LIKE 'Admin'));
INSERT INTO topics (id, title, category, creation_date, actual, creator_id) VALUES ((SELECT nextval('topic_id_sequence')), 'Final of UEFA Champions League', 'SPORT', '2022-04-12', true, (SELECT id FROM users WHERE username LIKE 'Admin'));

INSERT INTO posts (id, creation_date, text, topic_id, creator_id) VALUES ((SELECT nextval('post_id_sequence')), '2022-04-17', '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."', (SELECT id FROM topics WHERE title LIKE 'Spring Framework'), (SELECT id FROM users WHERE username LIKE 'User'));
INSERT INTO posts (id, creation_date, text, topic_id, creator_id) VALUES ((SELECT nextval('post_id_sequence')), '2022-04-20', '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."', (SELECT id FROM topics WHERE title LIKE 'Spring Framework'), (SELECT id FROM users WHERE username LIKE 'Karlo'));
INSERT INTO posts (id, creation_date, text, topic_id, creator_id) VALUES ((SELECT nextval('post_id_sequence')), '2022-05-06', '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."', (SELECT id FROM topics WHERE title LIKE 'Spring Boot Framework'), (SELECT id FROM users WHERE username LIKE 'User'));
INSERT INTO posts (id, creation_date, text, topic_id, creator_id) VALUES ((SELECT nextval('post_id_sequence')), '2022-03-17', '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."', (SELECT id FROM topics WHERE title LIKE 'Tesla - accumulators'), (SELECT id FROM users WHERE username LIKE 'Marko'));
INSERT INTO posts (id, creation_date, text, topic_id, creator_id) VALUES ((SELECT nextval('post_id_sequence')), '2022-04-10', '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."', (SELECT id FROM topics WHERE title LIKE 'Tesla - accumulators'), (SELECT id FROM users WHERE username LIKE 'Karlo'));